### ISSUE TITLE
Feature: Drop Shadow

### ISSUE THREAD

**Issue by gregziegan** [thebritican/annotation-editor#15]
It would be nice if the annotations had a nice shadow beneath them. This would help them appear "above" the image and give a crisp visual affect. There's some [svg filter code](https://github.com/thebritican/annotation-editor/blob/02207d0e56374877cfd52513b22362d9c9e08459/src/Annotator.elm#L1732) in the app now, but it's unused since i haven't gotten the filter right. Looking for any research/suggestions!

**Comment by gregziegan** [comment]
@bmson i know you know about some svg filters 😉
My WIP filter makes this quite ugly, you can see here:

https://ellie-app.com/HHbVvk6bY9a1/4

It's got issues because I haven't spent much time with it.

**Comment by gregziegan** [comment]
So this mostly solved now, but my current drop shadow filter causes some weird, weird bugs with svg lines at increments around of pi/4 🙀

**Comment by alanhogan** [comment]
Sound sounds … concerning. Puzzling. Let's take a look sometime

**Comment by gregziegan** [comment]
this will no longer matter if we use a `path` instead of an svg `line`. The new arrow and line will work with the shadow just fine!

**Comment by gregziegan** [comment]
closed with #71
