### ISSUE TITLE
Tweaks for fill & stroke icons

### ISSUE THREAD

**Issue by alanhogan** [thebritican/annotation-editor#20]
- Fill icons should just be solid circles
- The no-fill icon is an exception and should use a thin BLACK border but a RED diagonal line that does _not_ escape the containing circle. This is because the fill is null, not the circle/shape
- Stroke icons should be empty circles but with relatively thick strokes (maybe 3px as opposed to 1px for the no-fill icon)

My thoughts based on current implementation

**Comment by gregziegan** [comment]
- [x] Fill icons should just be solid circles
> * The no-fill icon is an exception and should use a thin BLACK border but a RED diagonal line that does not escape the containing circle. This is because the fill is null, not the circle/shape

How do you feel about the gray icon in #18?

- [x] Stroke icons should be empty circles but with relatively thick strokes (maybe 3px as opposed to 1px for the no-fill icon)

**Comment by gregziegan** [comment]
Going to close this as it's just a style preference for point 2 🙂
