### ISSUE TITLE
Deleting my mask left the gray overlay

### ISSUE THREAD

**Issue by alanhogan** [thebritican/annotation-editor#25]
[history-1091.txt](https://github.com/thebritican/goat/files/894813/history-1091.txt)

**Comment by gregziegan** [comment]
lolz. there's a super tiny, actually zero everything rectangle you accidentally drew. do you think the min size should be like... 2 pixels?
![image](https://cloud.githubusercontent.com/assets/3099999/24737616/dc4509e2-1a44-11e7-9773-f47fe9310a5b.png)

**Comment by alanhogan** [comment]
if you want me to bikeshed it, maybe 2 or 4 pixels. (I want to error on the small side because you never know what weird things users will want to do with the freedoms we give them. i don’t view this as a bad thing.)

**Comment by gregziegan** [comment]
I'm thinking we start the drawing at 0,0 and if the user draws anything smaller than 2 or 4 pixels we just cancel the drawing

**Comment by alanhogan** [comment]
oh FWIW a bigger min drawing distance makes sense for SPOTLIGHT shapes (e.g. the ones that created this issue) than REGULAR shapes. A spotlight shape so small you can't see 'through' it is dumb, and leads to confusion like mine. 

I didn't fully understand earlier - i lacked context when I replied by email. My bad.
