### ISSUE TITLE
Sometimes drawing does nothing

### ISSUE THREAD

**Issue by alanhogan** [thebritican/annotation-editor#29]
I drew more ellipses than were rendered. I have no idea why not, unless some drawings were interpreted as drags, but i did not see the image look like it was being dragged (usually).

[history-563.txt](https://github.com/thebritican/goat/files/894836/history-563.txt)

**Comment by gregziegan** [comment]
I was calling the absolute value function on a single value, not the expression. Therefore, the ellipses were getting negative `rx` and `ry` values and not rendering

**Comment by gregziegan** [comment]
If you import the history file with the newest commit, you'll see many more ellipses!

**Comment by alanhogan** [comment]
cool :)

**Comment by alanhogan** [comment]
Confirmed!
