### ISSUE TITLE
Clicking a shape can spontaneously delete it

### ISSUE THREAD

**Issue by alanhogan** [thebritican/annotation-editor#31]
… and undo won't undo it; or rather, it will, but it will undo too much.
Also, the control handles around the previously focused shape appear kind of glitchy after the spontaneous disappearance of the clicked shape. Aaand there are ghost control handles after undo.

I drew this:
![screen shot 2017-04-04 at 5 31 05 pm](https://cloud.githubusercontent.com/assets/6808/24684664/830f5546-195c-11e7-9d41-666d7e99a8e7.png)
(This is after undo. I didn't take a screenshot before the bug. hence the ghost placeholders you see)

Then I widened the pink box, I guess? I also messed with its stroke. Not sure about the order.

Then I clicked the red box (outside of the spotlight) and it disappeared forever.
![screen shot 2017-04-04 at 5 28 54 pm](https://cloud.githubusercontent.com/assets/6808/24684630/3c71f3f0-195c-11e7-8f14-623f36bcc19f.png)

[history-913.txt](https://github.com/thebritican/goat/files/894844/history-913.txt)

**Comment by alanhogan** [comment]
Hmm, i also can't export. (Update: Unrelated. #33)
```
Uncaught DOMException: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at HTMLImageElement.drawingImg.onload (file:///Users/ahogan/Repos/personal/goat/index.html:31:18)
```

**Comment by alanhogan** [comment]
Here is another demo of it. Enjoy mp4 and history export

(To be clear, in this, the spotlight shape spontaneously deleted. The earlier shape I deleted on purpose)

![goat bug](https://cloud.githubusercontent.com/assets/6808/24684823/bb74cc58-195d-11e7-9781-39128e6a04fe.gif)
History: [history-246.txt](https://github.com/thebritican/goat/files/894855/history-246.txt)
Video (better than the gif probably): https://cl.ly/362K291K0U1z

**Comment by gregziegan** [comment]
So, this bug was caused by keeping state in two places:

* The annotations array
* The union type: `AnnotationState`

Why was I keeping state in two places?
To avoid passing around an index in the annotations array.

With my current model, I just do:
```elm
{ model | annotations = Array.set index (someFunctionChangingAnnotation annotation) model.annotations }
```

But if i switch to passing around only the index, it becomes:
```elm
{ model | annotations =
  case Array.get index model.annotations of
    Just annotation ->
      Array.set index (someFunctionChangingAnnotation annotation ) model.annotations
    Nothing ->
      model.annotations
}
```

Well, who cares about boilerplate when you risk bugs like this? SO. I'll soon move to passing only the index around.
