### ISSUE TITLE
Ellipses should probably not draw from the middle

### ISSUE THREAD

**Issue by alanhogan** [thebritican/annotation-editor#32]
Most tools don't do this by default. Other shapes in GOAT draw from the corner. I think center drawing is fine, but maybe as a mode, not a default?

**Comment by gregziegan** [comment]
ya i have this as a todo in #24 but makes sense to be an issue as well

**Comment by gregziegan** [comment]
thanks @alanhogan for solvng this with #58 !

**Comment by alanhogan** [comment]
Glad to contribute!
