### ISSUE TITLE
Cannot export

### ISSUE THREAD

**Issue by alanhogan** [thebritican/annotation-editor#33]
Get this every time:

```
Uncaught DOMException: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at HTMLImageElement.drawingImg.onload (file:///Users/ahogan/Repos/personal/goat/index.html:31:18)
```

**Comment by gregziegan** [comment]
hmm i can?

![image](https://cloud.githubusercontent.com/assets/3099999/24716840/28852310-19e5-11e7-9a4f-74289ea4c2d5.png)

That error should only happen when the image you're annotating is from another domain. I added `canvas.crossOrigin = 'anonymous'` to get around it and i'm not seeing it 🤔

**Comment by alanhogan** [comment]
Dumb question but are you trying with the goat on the right too or only the cute goat

**Comment by alanhogan** [comment]
I just got the same error, this time in Safari, on gregziegan.com/goat, and using the cute goat

**Comment by alanhogan** [comment]
actually the error this time was that `canvas.toBlob` was undefined

**Comment by gregziegan** [comment]
I've never seen the `canvas.toBlob` undefined. let's pair on this so i can repro on your machine
