### ISSUE TITLE
Image exported larger than it was imported

### ISSUE THREAD

**Issue by alanhogan** [thebritican/annotation-editor#36]
That feels weird to me — and is kind of lossy, you know?

**Comment by alanhogan** [comment]
![screen shot 2017-03-31 at 9 43 26 pm](https://cloud.githubusercontent.com/assets/6808/24775761/00b1a23e-1ad3-11e7-826b-97f03ba399f6.png)

   ↓
_became_
   ↓

![d648fd25-9976-41bf-a1ae-bc6f3e6eb48a](https://cloud.githubusercontent.com/assets/6808/24775763/027ac852-1ad3-11e7-8ea9-bb247dc39b61.png)


That’s 781 × 848 becoming 1562 × 1696. I guess this is because I was on Retina.

**Comment by gregziegan** [comment]
I'll be looking into this on tomorrow/Monday when I work more on the image dimension & export work into the Zendesk Editor App location
