### ISSUE TITLE
Cannot move an annotation that was drawn before a spotlight annotation

### ISSUE THREAD

**Issue by gregziegan** [thebritican/annotation-editor#5]
If the annotation is beneath the svg mask, the mask responds to the events instead. 

Perhaps all annotations should live above the mask?

See line 203:
[history-203.txt](https://github.com/thebritican/annotation-editor/files/861871/history-203.txt)

**Comment by alanhogan** [comment]
hey you can probably just set the pointer-events property on the mask so that you can click 'through' it :)

**Comment by gregziegan** [comment]
thanks @alanhogan super easy
