### ISSUE TITLE
Can't use mouse to select/edit text

### ISSUE THREAD

**Issue by alanhogan** [thebritican/annotation-editor#50]
Clicking text while in text-edit mode exits text-edit mode.

I’d want to be able to place the cursor and/or select a substring.

![2017-04-11 goat text editing mov](https://cloud.githubusercontent.com/assets/6808/24924029/4322e546-1ea8-11e7-96de-f0a1ddcbbcb1.gif)

**Comment by gregziegan** [comment]
fixed this with https://github.com/thebritican/goat/commit/76a361a05d5f1dff70582ed6bc43d38c799762a2#diff-1eaede071ba25e558e0994b60c999defR922
