### ISSUE TITLE
Feature: Improve arrow

### ISSUE THREAD

**Issue by gregziegan** [thebritican/annotation-editor#54]
The arrow is pretty ugly. It's a boring triangle. Looking to replace it with a nicer looking arrow

**Comment by gregziegan** [comment]
Could use a new arrow head definition, @alanhogan? 🙏

**Comment by alanhogan** [comment]
arrowhead.svg:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="82" height="77" viewBox="0 0 82 77">
  <polygon fill-rule="evenodd" points="20.5 38.5 2.5 -2.5 79.5 38.5 2.5 79.5" transform="rotate(-90 41 38.5)"/>
</svg>
```

**Comment by gregziegan** [comment]
![screen recording 2017-04-18 at 12 39 am](https://cloud.githubusercontent.com/assets/3099999/25119568/98afc2aa-23cf-11e7-9d9f-8bb6707dd069.gif)

I think we can still do a little better by making the line in the arrow gradually narrow. So that'll be one more svg 😄

**Comment by alanhogan** [comment]
Digging this

**Comment by alanhogan** [comment]
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="26" height="78" viewBox="0 0 26 78">
  <path fill-rule="evenodd" d="M21,70 L26,0 L0,0 L4.99625706,69.9475988 C4.99745391,69.9650475 4.99870125,69.982511 5,70 C5.37717014,75.0789931 8.581722,78 13,78 C17.418278,78 20.6640625,75.2675781 21,70 Z"/>
</svg>
```

**Comment by alanhogan** [comment]
^ candidate arrow tail. actually it might be tricky as it includes a rounded end which will probably look dumb stretched. hold on

**Comment by alanhogan** [comment]
Tail end:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="26" height="8" viewBox="0 0 26 8">
  <path fill-rule="evenodd" d="M21,70 L26,0 L0,0 L4.99625706,69.9475988 C4.99745391,69.9650475 4.99870125,69.982511 5,70 C5.37717014,75.0789931 8.581722,78 13,78 C17.418278,78 20.6640625,75.2675781 21,70 Z" transform="translate(0 -70)"/>
</svg>
```

Tail mid:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="26" height="70" viewBox="0 0 26 70">
  <path fill-rule="evenodd" d="M21,70 L26,0 L0,0 L4.99625706,69.9475988 C4.99745391,69.9650475 4.99870125,69.982511 5,70 C5.37717014,75.0789931 8.581722,78 13,78 C17.418278,78 20.6640625,75.2675781 21,70 Z"/>
</svg>
```

that might be a better approach. Can also easily do a tapering tail with no roundedness at all

i have more ideals so hang on

But what I just gave you looks like this:

<img width="201" alt="screen shot 2017-04-18 at 10 52 54 am" src="https://cloud.githubusercontent.com/assets/6808/25145161/35a360d0-2425-11e7-81a0-652edceaf8fd.png">

**Comment by alanhogan** [comment]
<img width="191" alt="screen shot 2017-04-18 at 10 59 16 am" src="https://cloud.githubusercontent.com/assets/6808/25145460/1b857e94-2426-11e7-9088-493c82e48a78.png">

But why be straight when you can gently curve? I like this also because the joint between the end and arrow body is purely vertical, which means it should scale to extremes without disjointedness.

Tail mid:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="26" height="70" viewBox="0 0 26 70">
  <path fill-rule="evenodd" d="M4.21329638e-14,-2.66453526e-15 L26,-2.66453526e-15 C21,38 21,60 21,70 L5,70 C5,60 5,38 4.21329638e-14,-2.66453526e-15 Z M13,78 C8.581722,78 5,75 5,70 L21,70 C21,75 17.418278,78 13,78 Z"/>
</svg>
```

Tail end:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="26" height="8" viewBox="0 0 26 8">
  <path fill-rule="evenodd" d="M4.21329638e-14,-2.66453526e-15 L26,-2.66453526e-15 C21,38 21,60 21,70 L5,70 C5,60 5,38 4.21329638e-14,-2.66453526e-15 Z M13,78 C8.581722,78 5,75 5,70 L21,70 C21,75 17.418278,78 13,78 Z" transform="translate(0 -70)"/>
</svg>
```

**Comment by alanhogan** [comment]
You can also just use Tail Mid without Tail End. Whichever you/we prefer. I’m not entirely sure how we will feel about the rounded end on the tail.

**Comment by alanhogan** [comment]
i am realizing those exports suck as they both include the entire tail shape but just cut it to a different view-box. fixing…

**Comment by alanhogan** [comment]
Okay. Here please find proper exports. And the arrowhead has a little less of a gap in the middle, to reduce the chance of a gap showing during reassembly.

Arrowhead:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="82" height="77" viewBox="0 0 82 77">
  <polygon fill-rule="evenodd" points="16.361 29.676 2.5 -2.5 79.5 38.5 2.5 79.5 16.361 48.49" transform="rotate(-90 41 38.5)"/>
</svg>
```

Tail mid:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="26" height="70" viewBox="0 0 26 70">
  <path fill-rule="evenodd" d="M4.21329638e-14,-2.66453526e-15 L26,-2.66453526e-15 C21,38 21,60 21,70 L5,70 C5,60 5,38 4.21329638e-14,-2.66453526e-15 Z"/>
</svg>
```

Tail end:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="26" height="8" viewBox="0 0 26 8">
  <path fill-rule="evenodd" d="M13,8 C17.418278,8 21,5 21,0 L5,0 C5,5 8.581722,8 13,8 Z"/>
</svg>
```

**Comment by alanhogan** [comment]
<img width="475" alt="what it looks like" src="https://cloud.githubusercontent.com/assets/6808/25146967/b39d01e4-242a-11e7-856b-f90141f0f7f7.png">

**Comment by alanhogan** [comment]
(I kept the viewboxes for the tail mid & end the same width so that you can scale them at the same ratio to get perfectly contiguous resulting shapes.)

**Comment by gregziegan** [comment]
Let's track any changes to the arrow from here on out in a new issue thread (if there needs to be any adjustments!). I'd say with #68 , this is closed
