### ISSUE TITLE
Sometimes copy/paste fails

### ISSUE THREAD

**Issue by alanhogan** [thebritican/annotation-editor#56]
I copy/pasted the spacesuit neck with ⌘-C, ⌘-V but nothing happened

[history-750.txt](https://github.com/thebritican/goat/files/924057/history-750.txt)
![d12579c9-5726-4320-85b5-494ed98df0db](https://cloud.githubusercontent.com/assets/6808/25068250/76aac6dc-2212-11e7-842e-8f907929ed89.png)

**Comment by gregziegan** [comment]
it's when the right-hand command key is used (93)! forgot to account for that case. only handling 91 right now

**Comment by gregziegan** [comment]
Closed with https://github.com/thebritican/goat/commit/817c71efb3d162ee38047c536802b944ac7ee59c

**Comment by gregziegan** [comment]
thanks for the debugger file, @alanhogan ! invaluable to see the keycode you were pressing in the messages 👍

**Comment by alanhogan** [comment]
that's a really cool example of the debugger being useful
