### ISSUE TITLE
Button compresses svg below drawn height

### ISSUE THREAD

**Issue by alanhogan** [thebritican/annotation-editor#64]
The pixelate icon is pixel-fitted to its viewBox dimensions, 20x20, but the button that contains it only leaves 18px. The result is blurry edges.

_As intended_
![screen shot 2017-04-23 at 5 34 29 pm](https://cloud.githubusercontent.com/assets/6808/25318863/5136edb0-284b-11e7-8193-cdeb7e12cec9.png)

_As rendered_
![screen shot 2017-04-23 at 5 34 41 pm](https://cloud.githubusercontent.com/assets/6808/25318865/52c8a402-284b-11e7-8c44-fa77c98c9c29.png)

**Comment by gregziegan** [comment]
would you mind making a pr for this one @alanhogan ? wasn't sure how to fix the CSS without breaking the button layout
