### ISSUE TITLE
Feature: Alter ordering of annotations

### ISSUE THREAD

**Issue by gregziegan** [thebritican/annotation-editor#7]
Looking for ideas here:

Is a right click context menu with "send to front, send to back, etc" the best idea?
Should I offer this?
Should reordering happen by "the last thing i drew OR edited is on top"?

**Comment by gregziegan** [comment]
@alanhogan any thoughts here?

**Comment by alanhogan** [comment]
> Is a right click context menu with "send to front, send to back, etc" the best idea?
> Should I offer this?

I would like it

> Should reordering happen by "the last thing i drew OR edited is on top"?

Should editing something make it the new top? Probably not! Dunno, we could try it, but it may be frustrating.

**Comment by gregziegan** [comment]
@alanhogan check it out ☝️
