### ISSUE TITLE
What if such tool worked on every live webpage

### ISSUE THREAD

**Issue by vojtatranta** [thebritican/annotation-editor#86]
I had an idea to build such tool, but it would work on live webpages. The idea is that you could annotate and draw on any website and tool would generate an url with you annotation and live website beneath it, it could be much more useful....

**Comment by gregziegan** [comment]
I could see this working as an extension, but i'm not sure how you'd guarantee the correct positioning of annotations if the website changes its styles/content... 🤔

**Comment by alanhogan** [comment]
There is a long tradition of apps and sites that try to do this. 

Seems out of scope to me

**Comment by gregziegan** [comment]
I think this is a cool idea and you should feel free to message me on the elm lang slack to work through some ideas you have! But, i think it's out of scope for G.O.A.T. so i'm closing the issue :)
